### ISSUE TITLE
Some offsets seem to be problematic

### ISSUE THREAD

**Issue by pouryafard75** [SpoonLabs/gumtree-spoon-ast-diff#327] opened 2024-09-23 07:51 UTC
This is a continuation of the previously reported issue https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/323. Thank you very much  @algomaster99  @monperrus for the prompt fix.

For the following code snippet:
```
class Test {
    @Override
    public int hashCode() {
        return -1;
    }
}
```

I get the following tree:
```
root [0,0]
    RootPac: unnamed package [0,0]
        Class: Test [0,80]
            Method: hashCode [17,78]
                RETURN_TYPE: int [0,0]
                Modifiers_Method [17,78]
                    Modifier: public [31,36]
                Annotation: java.lang.Override [17,25]
                Return: return [63,72]
                    UnaryOperator: NEG [70,71]
                        Literal: 1 [71,71]
```

The problems that you can address here:
- Literal has the same start and offset (71).
- RETURN_TYPE int has 0s as start and end.
- Modifer public has 36 and 31 while public takes 6 characters!

**Comment by algomaster99** [comment] 2024-09-23 11:10
Hi @pouryafard75 !

I am unable to reproduce the error. I get:
```
root [0,0]
    RootPac: unnamed package [0,0]
        Class: Test [0,80]
            Method: hashCode [17,78]
                RETURN_TYPE: int [38,40]
                Modifiers_Method [31,36]
                    Modifier: public [31,36]
                Annotation: java.lang.Override [17,25]
                Return: return [63,72]
                    UnaryOperator: NEG [70,71]
                        Literal: 1 [71,71]
```
`RETURN_TYPE` is `[38,40]`.

> Literal has the same start and offset (71).
> Modifer public has 36 and 31 while public takes 6 characters!

This is because of https://github.com/INRIA/spoon/issues/5980#issuecomment-2366855384. @SirYwell, could you recommend APIs that would give the correct lengths. Right now, we could add 1 to the current result and get the correct length.

**Comment by algomaster99** [comment] 2024-09-23 13:16
Thanks!

**Comment by pouryafard75** [comment] 2024-09-23 14:49
@algomaster99 
Could you please run the AstComperator with the following arguments?
src/test/resources/examples/annotations/left.java src/test/resources/examples/annotations/right.java

and print the tree as follows

```
final Diff result = new AstComparator().compare(new File(args[0]), new File(args[1]));
System.out.println(result.getMappingsComp().src.toTreeString());
```

This is what I get:
```
root [0,0]
    RootPac: unnamed package [0,0]
        Class: Test [0,80]
            Method: hashCode [17,78]
                RETURN_TYPE: int [0,0]
                Modifiers_Method [17,78]
                    Modifier: public [31,36]
                Annotation: java.lang.Override [17,25]
                Return: return [63,72]
                    UnaryOperator: NEG [70,71]
                        Literal: 1 [71,71]
```

**Comment by algomaster99** [comment] 2024-09-23 17:29
I still get this as output:
```java
root [0,0]
    RootPac: unnamed package [0,0]
        Class: Test [0,80]
            Method: hashCode [17,78]
                RETURN_TYPE: int [38,40]
                Modifiers_Method [31,36]
                    Modifier: public [31,36]
                Annotation: java.lang.Override [17,25]
                Return: return [63,72]
                    UnaryOperator: NEG [70,71]
                        Literal: 1 [71,71]
```
This is very strange.

I also have a [CI test](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/f5e6ff26b770967dc2bd8ea877d07e340f713ca8/src/test/java/gumtree/spoon/SourcePositionTest.java#L92) ensuring this behaviour. `RETURN_TYPE` must be enclosed within `hashCode` so its start position must be `>=17` and end position must be `<=78`.
And here is the [specific test case](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/test/resources/source-positions/Return.java).

I can only recommend using the [latest release](https://central.sonatype.com/artifact/fr.inria.gforge.spoon.labs/gumtree-spoon-ast-diff/1.82).

**Comment by pouryafard75** [comment] 2024-09-23 18:00
Okay my bad, I was experimenting with https://github.com/SpoonLabs/gumtree-spoon-ast-diff/pull/325/commits/28af6e1613ead5b4af63bb0d583220d9a94d4647 since you had mentioned me back then. I also get 

`RETURN_TYPE: int [38,40]`, however since the end offsets are off by 1, I can't test it properly.

**Comment by algomaster99** [comment] 2024-09-23 18:10
Sorry for not being clear initially 😅

> however since the end offsets are off by 1, I can't test it properly.

Good news is that all are offset by 1 so you can always add 1 to the end position. If you cannot do this, then you can add an API to https://github.com/inria/spoon like SirYwell suggests by first opening an issue there.

**Comment by algomaster99** [comment] 2024-09-23 19:52
Closing. Feel free to open another issue in case you encounter some problems :)

**Closed by algomaster99** 2024-09-23 19:52 UTC
